development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:d4dca68d7778e6ea5f9ec258f38d8313@pike.redistogo.com:10006/
  channel_prefix: instatalk_production
